/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;


#if !SILVERLIGHT
[Serializable]
#endif
public partial class PublishCommandRequest : TBase
{
  private string _clientId;
  private GameCommand _gameCommand;

  public string ClientId
  {
    get
    {
      return _clientId;
    }
    set
    {
      __isset.clientId = true;
      this._clientId = value;
    }
  }

  public GameCommand GameCommand
  {
    get
    {
      return _gameCommand;
    }
    set
    {
      __isset.gameCommand = true;
      this._gameCommand = value;
    }
  }


  public Isset __isset;
  #if !SILVERLIGHT
  [Serializable]
  #endif
  public struct Isset {
    public bool clientId;
    public bool gameCommand;
  }

  public PublishCommandRequest() {
  }

  public void Read (TProtocol iprot)
  {
    iprot.IncrementRecursionDepth();
    try
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.String) {
              ClientId = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.Struct) {
              GameCommand = new GameCommand();
              GameCommand.Read(iprot);
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }
    finally
    {
      iprot.DecrementRecursionDepth();
    }
  }

  public void Write(TProtocol oprot) {
    oprot.IncrementRecursionDepth();
    try
    {
      TStruct struc = new TStruct("PublishCommandRequest");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (ClientId != null && __isset.clientId) {
        field.Name = "clientId";
        field.Type = TType.String;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(ClientId);
        oprot.WriteFieldEnd();
      }
      if (GameCommand != null && __isset.gameCommand) {
        field.Name = "gameCommand";
        field.Type = TType.Struct;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        GameCommand.Write(oprot);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }
    finally
    {
      oprot.DecrementRecursionDepth();
    }
  }

  public override string ToString() {
    StringBuilder __sb = new StringBuilder("PublishCommandRequest(");
    bool __first = true;
    if (ClientId != null && __isset.clientId) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("ClientId: ");
      __sb.Append(ClientId);
    }
    if (GameCommand != null && __isset.gameCommand) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("GameCommand: ");
      __sb.Append(GameCommand== null ? "<null>" : GameCommand.ToString());
    }
    __sb.Append(")");
    return __sb.ToString();
  }

}

